version: 2.1

jobs:
  ruby_build:
    docker:
      - image: circleci/ruby:2.5.1
    steps: 
      - checkout
      - run: gem install bundler
      - run: ls
      - run: bundle install --gemfile ./ruby/Gemfile # we are not in root folder so specifying where to pick Gemfile from
  
  ruby_test:
    docker:
      - image: circleci/ruby:2.5.1
    steps: 
      - checkout
      - run:
          working_directory: ./ruby
          command: gem install bundler
      - run:
          working_directory: ./ruby
          command: bundle install
      - run:
          working_directory: ./ruby
          command: rspec programs/*
  

  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: |  
                ls
                sudo apt-get install unzip
                wget https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip
                unzip terraform_0.12.29_linux_amd64.zip
                sudo mv terraform /usr/local/bin/

      - run: | 
                terraform --version
      - run: terraform init
      - run: terraform plan
      - run: terraform apply 

workflows:
  ruby_build_test:
    jobs:
      # - ruby_build:
      #     filters:
      #       branches:
      #         only: 
      #           - master
      #           - /(ruby-.*)|(ci-.*)/
      # - ruby_test:
      #     requires:
      #       - ruby_build
      #     filters:
      #       branches:
      #         only:
      #           - master
      #           - /(ruby-.*)|(ci-.*)/
      - deploy

        
      
    