version: 2.1

jobs:
  ruby_build:
    docker:
      - image: circleci/ruby:2.5.1
    steps: 
      - checkout
      - run: gem install bundler
      - run: ls
      - run: bundle install --gemfile ./ruby/Gemfile # we are not in root folder so specifying where to pick Gemfile from
  
  ruby_test:
    docker:
      - image: circleci/ruby:2.5.1
    steps: 
      - checkout
      - run:
          working_directory: ./ruby
          command: gem install bundler
      - run:
          working_directory: ./ruby
          command: bundle install
      - run:
          working_directory: ./ruby
          command: rspec programs/*

workflows:
  ruby_build_test:
    jobs:
      - ruby_build:
          filters:
            branches:
              only: 
                - master
                - /(ruby-.*)|(ci-.*)/
      - ruby_test:
          requires:
            - ruby_build
          filters:
            branches:
              only:
                - master
                - /(ruby-.*)|(ci-.*)/

        
      
    